# Some wayland envs
env = NIXOS_OZONE_WL,1
env = GDK_BACKEND,wayland,x11
env = CLUTTER_BACKEND,wayland
env = SDL_VIDEODRIVER,wayland
env = MOZ_ENABLE_WAYLAND,1
env = QT_QPA_PLATFORM,wayland
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = _JAVA_AWT_WM_NONREPARENTING,1
