general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = hyprlock --immediate     # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.

    ignore_dbus_inhibit = false

    grace = 8           # seconds before lock is enforced — mouse/key activity cancels it
    no_fade_in = false  # smooth fade in
    no_fade_out = false
    hide_cursor = true
}

listener {
    timeout = 600                            # 10 min → lock
    on-timeout = hyprlock
}

listener {
    timeout = 1200                           # 20 min → displays off
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 1800                           # 30 min → suspend
    on-timeout = systemctl suspend
}
