# #######################################################################################
# Variables
# #######################################################################################

# Main modification key.
# SUPER is the Windows/Command key.
# Use ALT for the Alt key if you prefer Mod1.
$mod = ALT

# Home row direction keys, like vim
$left = h
$down = j
$up = k
$right = l

# Your preferred terminal emulator
$term = gabyx::term

# Application and script shortcuts
$file_manager = gabyx::file-manager-menu
$launcher_menu = gabyx::launcher-menu
$power_menu = gabyx::power-menu
$wireless_menu = gabyx::wireless-menu
$network_menu = gabyx::network-menu
$bluetooth_menu = gabyx::bluetooth-menu
$emoji_menu = gabyx::emoji-menu
$systemd_menu = gabyx::systemd-menu
$procs_menu = gabyx::procs-menu
$sound_menu = gabyx::sound-menu
$calculator_menu = gabyx::calculator-menu
$screenshot_menu = gabyx::screenshot-menu
$screenrecord_menu = gabyx::screenrecord-menu
$color_picker_menu = gabyx::color-picker-menu
$clipboard_menu = gabyx::clipboard-menu

# Workspace Names
# Using 'name:' allows for persistent, named workspaces.
$ws1 = name:1:  
$ws2 = name:2:  
$ws3 = name:3:  
$ws4 = name:4:  
$ws5 = name:5:  
$ws6 = name:6:  
$ws7 = name:7:  
$ws8 = name:8:  
$ws9 = name:9:  
$ws10 = name:0:  󱕴

# For convenience, mapping names to app workspaces
$comm_ws = $ws7
$mail_ws = $ws8
$web_ws = $ws9
$creds_ws = $ws10
