# #######################################################################################
# Window Rules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# #######################################################################################

# Assign applications to workspaces

# Dialogs and pop-ups

# Floating apps
windowrule = tag +file-manager, match:class ^.*([Tt]hunar|[Nn]autilus).*$
windowrule = tag +terminal, match:class ^.*(ghostty|wezterm|kitty).*

windowrule = tag +browser, match:class ^.*(brave|[Ff]irefox|chrome).*$
windowrule = tag +chat,    match:class ^.*(signal|element|slack).*$
windowrule = tag +mail,    match:class ^.*(evolution).*$
windowrule = tag +secrets, match:class ^.*(bitwarden).*$

windowrule = tag +settings, match:class ^.*(file-roller|FileRoller)$
windowrule = tag +settings, match:class ^.*(nm-applet|nm-connection-editor|blueman-manager|wihotspot(-gui)?).*$
windowrule = tag +settings, match:class ^.*(nwg-displays).*$
windowrule = tag +settings, match:class ^.*(gnome-disks|wihotspot(-gui)).*$
windowrule = tag +settings, match:class ^.*(copyq|qalculate-gtk|font-manager).*$
windowrule = tag +settings, match:title (?i)^(open|save) (file|folder|as)$
windowrule = tag +settings, match:title (?i)^preferences$
windowrule = tag +settings, match:title (?i)^dialog$
windowrule = tag +settings, match:title (?i)^menu$

# Apply setting to tags.
windowrule = size 70% 60%, float true, match:tag settings*
windowrule = workspace $web_ws,   match:tag browser*
windowrule = workspace $mail_ws,  match:tag mail*
windowrule = workspace $comm_ws,  match:tag chat*
windowrule = workspace $creds_ws, match:tag secrets*

# Replicating smart gaps
# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule {
    name = no-gaps-wtv1
    match:float = false
    match:workspace = w[tv1]

    border_size = 0
    rounding = 0
}

windowrule {
    name = no-gaps-f1
    match:float = false
    match:workspace = f[1]

    border_size = 0
    rounding = 0
}
