# #######################################################################################
# Monitor Configuration
#
# You can get output names by running `hyprctl monitors`
# Format: monitor = <name>,<resolution>,<position>,<scale>
# Use 'preferred' for resolution and 'auto' for position to let Hyprland decide.
# #######################################################################################

master {
    orientation = left
}

workspace = $ws1, persistent:true, monitor:$primaryDisp
workspace = $ws2, persistent:true, monitor:$primaryDisp
workspace = $ws3, persistent:true, monitor:$primaryDisp
workspace = $ws4, persistent:true, monitor:$primaryDisp
workspace = $ws5, persistent:true, monitor:$primaryDisp
workspace = $ws6, persistent:true, monitor:$primaryDisp

workspace = $comm-ws, persistent:true,  monitor:$secondaryDisp
workspace = $mail-ws, persistent:true,  monitor:$secondaryDisp
workspace = $web-ws, persistent:true,   monitor:$secondaryDisp
workspace = $creds-ws, persistent:true, monitor:$secondaryDisp

# Assign a placeholder workspace to a laptop display if needed
workspace = 11, monitor:eDP-1
