# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/virtualisation/qemu-vm.nix")
    ./hardware-disks-ext4.nix
    ./qemu.nix
  ];

  boot.initrd.availableKernelModules = [
    "ata_piix"
    "uhci_hcd"
    "virtio_pci"
    "virtio_blk"
  ];

  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-intel"
    "kvm-arm"
  ];
  boot.extraModulePackages = [ ];

  # Set the platform where the NixOS configuration will run.
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Configure the disks with disko:
  # https://github.com/nix-community/disko
  # Examples here: https://github.com/nix-community/disko/tree/master/example

  # Basic Disko config (more is in hardware-disks-ext4)
  disko.memSize = 5000;

}
