# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  modulesPath,
  ...
}:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/6fbd4c98-9ca9-4a8a-966f-24491282220b";
    fsType = "btrfs";
    options = [ "subvol=root" ];
  };

  boot.initrd.luks.devices."enc-physical-vol".device =
    "/dev/disk/by-uuid/c770819c-1193-4a1e-a94d-3e13dc634a2e";

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/6fbd4c98-9ca9-4a8a-966f-24491282220b";
    fsType = "btrfs";
    options = [
      "subvol=home"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/6fbd4c98-9ca9-4a8a-966f-24491282220b";
    fsType = "btrfs";
    options = [
      "subvol=nix"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/6fbd4c98-9ca9-4a8a-966f-24491282220b";
    fsType = "btrfs";
    options = [
      "subvol=persist"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/persist/etc" = {
    device = "/dev/disk/by-uuid/6fbd4c98-9ca9-4a8a-966f-24491282220b";
    fsType = "btrfs";
    depends = [ "/persist" ];
    options = [
      "subvol=persist/etc"
      "compress=zstd"
      "noatime"
    ];
    neededForBoot = true;
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/6fbd4c98-9ca9-4a8a-966f-24491282220b";
    fsType = "btrfs";
    options = [
      "subvol=log"
      "compress=zstd"
      "noatime"
    ];
    neededForBoot = true;
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/6fbd4c98-9ca9-4a8a-966f-24491282220b";
    fsType = "btrfs";
    options = [
      "subvol=swap"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1ECB-0D03";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ { device = "/swap/swapfile"; } ];
}
