set positional-arguments
set fallback := true
set shell := ["bash", "-cue"]
root_dir := `git rev-parse --show-toplevel`

[private]
default:
    just --list

# Edit a encrypted file with agenix.
edit file:
    agenix -i "{{root_dir}}/secrets/.env" -e "{{file}}" && \
        just move-all-secrets

# Reencrypt all secrets.
renecrypt:
    agenix -i "{{root_dir}}/secrets/.env" -r && \
        just move-all-secrets

# Login to the ssh storage.
ssh-storage:
    #!/usr/bin/env bash
    set -eu

    function cleanup() {
        rm /run/user/1000/priv || true
    }

    trap cleanup EXIT

    sudo agenix -d backup-storage-ssh-ed25519.age -i ~/.ssh/host-ed25519 > /run/user/1000/priv
    chmod 600 /run/user/1000/priv
    ssh -p 23 -i /run/user/1000/priv \
        u492021@u492021.your-storagebox.de
