set positional-arguments
set shell := ["bash", "-cue"]
root_dir := justfile_directory()

ssh-storage:
    #!/usr/bin/env bash
    set -eu

    function cleanup() {
        rm /run/user/1000/priv || true
    }

    trap cleanup EXIT

    sudo agenix -d backup-storage-ssh-ed25519.age -i ~/.ssh/host-ed25519 > /run/user/1000/priv
    chmod 600 /run/user/1000/priv
    ssh -p 23 -i /run/user/1000/priv \
        u492021@u492021.your-storagebox.de
