set positional-arguments
set fallback := true
set shell := ["bash", "-cue"]
root_dir := `git rev-parse --show-toplevel`

[private]
default:
    just --list

# Edit a encrypted file with agenix.
# Usage with:
# sudo -E SOPS_AGE_KEY_FILE=/persist/etc/ssh/host-ed25519 just edit read-nix-cache-swisscustodian.age
edit file:
    #!/usr/bin/env bash
    set -eu
    agenix -i "$SOPS_AGE_KEY_FILE" -e "{{file}}" && \
        just move-all-secrets

# Reencrypt all secrets.
renecrypt:
    #!/usr/bin/env bash
    set -eu
    agenix -i "$SOPS_AGE_KEY_FILE" -r && \
        just move-all-secrets

# Login to the ssh storage.
ssh-storage:
    #!/usr/bin/env bash
    set -eu

    function cleanup() {
        rm /run/user/1000/priv || true
    }

    trap cleanup EXIT

    sudo agenix -d backup-storage-ssh-ed25519.age -i ~/.ssh/host-ed25519 > /run/user/1000/priv
    chmod 600 /run/user/1000/priv
    ssh -p 23 -i /run/user/1000/priv \
        u492021@u492021.your-storagebox.de
